version: '3.8'

services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn 'intellect_agent:create_app()' --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A intellect_agent.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
